
Import('env')

env.Append( CCFLAGS=' -I./config -I./libapp' )

env.Library( 'libapp', Split(
	""" 
		app.cpp
		bitset.cpp
		dbg.cpp
		file.cpp
		md5.c
		parser.cpp
		resolver.cpp
		sock.cpp
		str.cpp
		stream.cpp
		thread.cpp
		timer.cpp
		types.cpp
		url.cpp
		util.cpp
		valmap.cpp
		variant.cpp
	""" ) )
	